### ISSUE TITLE
line 26 compares itself causing the condition never to fire

### ISSUE THREAD

**Issue by sktg84** [bhattbhavesh91/flipkart-price-tracker#1]
![image](https://user-images.githubusercontent.com/45620176/120964658-465ada80-c781-11eb-8d85-9f2c9ad376bd.png)

In line 26, we see that there is a loop that never gets fired. Needs to compare with the last scan or the cut off value...

**Comment by bhattbhavesh91** [comment]
Thanks for pointing this out! I have modified the script!

**Comment by sktg84** [comment]
Awesome... Lightning fast reply...
